version: v1

variables: # 定义
  region1: # 枚举类型,值为cn,hk
    - cn
    - hk
  region2:
    - us
    - uk
  str_value: hello world # 字符串类型
  username: webook
  password: webook_password
  tmpl1:
    template: # 模版类型
      expr: ${region}.${role}.meoying.com:3306 # 表达式
      placeholders: # 表达式中的占位符列表
        region: # 占位符名称, 此时region为枚举类型
          - cn
          - hk
        role: master # 字符串类型
      # 模版类型需要提供求值方法Evaluate(placeholders) ([]string, error)
  tmpl_value:
    template: # 模版类型
      expr: ${region}.meoying.com:3306 # 表达式
      placeholders: # 表达式中的占位符列表
        region: # 引用类型, 引用之前定义的变量, 可以是多个
          ref:
            - values.region1
            - values.region2
  db_key: # 生成规则名称
    hash: # 生成规则类型 —— 哈希类型 表示 将 user_id%10
      key: user_id # 分片键user_id
      base: 10
  tab_key:
    hash:
      key: user_id
      base: 32

# 定义数据库名生成规则
databases:
  user_shard:
    template:
      expr: "user_db_${key}"
      placeholders:
        key:
          ref: values.db_key

  order_shard:
    template:
      expr: "order_db_${key}"
      placeholders:
        key:
          ref:
            - values.db_key
  payment: payment_db # 字符串类型

# 定义数据源名生成规则、
datasources:
  mts_ds:
    master: webook:134root@tcp(cn.meoying.com:3306)/?charset=utf8mb4&parseTime=True
    slave:
      template:
        expr: webook:webook@tcp(${region}.slave.meoying.com:3306)/?charset=utf8mb4&parseTime=True
        placeholders:
        region:
          ref:
            - values.region2
  cos_ds:
    master:
      ref:
        - path: datasources.cos_ds.master
    slave:
      username: webook
      password: 134root
      address: cn.slave.meoying.com:3306
      # parameters 参数可选
    shadow:
      template:
        expr: webook:webook@tcp(${region}.slave.meoying.com:3306)/${db}?ccesec # 表达式
        placeholders: # 表达式中的占位符列表
          region: # 占位符名称
            enum: # 占位符类型为枚举,值为cn,hk
              - cn
              - hk
          db:
            ref:
              - databases.order_shard
              - databases.payment_shard
    mts_ds_copy:
      master:
        ref:
          - datasources.mts_ds.master # 表示 mts_ds_copy 与 mts_ds 一致
      slave:
        template: # 模版类型
          expr: webook:webook@tcp(${region}.slave.meoying.com:3306)/${db}?k1=v1&k3=v3 # 表达式
          placeholders: # 表达式中的占位符列表
            region: # 占位符名称
              ref:
                - values.region2
            db:
              ref:
                - databases.user_shard
                - databases.order_shard

tables: # 定义数据库表生成规则
  order: # 逻辑表名
    sharding:
      datasource:
        master: root:root@tcp(127.0.0.1:13306)/?charset=utf8mb4&parseTime=True&loc=Local
        slave: root:root@tcp(127.0.0.1:13306)/?charset=utf8mb4&parseTime=True&loc=Local
      database:
        order_db:
          template:
            expr: "local_sharding_plugin_db_${key}"
            placeholders:
              key:
                hash:
                  key: user_id
                  base: 3
      table: order_tab