version: v1

variables: # 定义公共变量, 可选, 可以定义任何合法变量
  # 字符串
  str_value: hello world
  username: webook
  password: webook_password
  # 枚举
  region1:
    - cn
    - hk
  region2:
    - us
    - uk
  # 引用
  ref_key:
    ref: variables.region1
  tmpl1:
    template: # 模版类型,复合类型
      expr: ${region}.${role}.meoying.com:3306 # 表达式
      placeholders: # 表达式中的占位符列表
        region: # 占位符名称, 此时region为枚举类型
          - cn
          - hk
        role: master # 字符串类型
  tmpl_value:
    template:
      expr: ${region}.meoying.com:3306
      placeholders:
        region: # 引用类型, 引用之前定义的变量
          ref: variables.region1
  # 哈希类型
  db_key:
    hash:
      key: user_id # 分片键user_id
      base: 10
  tab_key:
    hash:
      key: user_id
      base: 32


# 定义数据库名生成规则,可选,
databases:
  # 模版类型,复合类型
  user_shard:
    template:
      expr: "user_db_${key}"
      placeholders:
        key:
          ref: variables.db_key
  # 模版类型,复合类型
  order_shard:
    template:
      expr: "order_db_${key}"
      placeholders:
        key:
          ref:
            - variables.db_key
  # 字符串类型
  payment: payment_db

# 定义数据源名生成规则,可选,定义变量要符合规则
datasources:
  mts_ds:
    # dns中无db名信息与db定义解耦合
    master: webook:134root@tcp(cn.meoying.com:3306)/?charset=utf8mb4&parseTime=True
    slave:
      template:
        expr: webook:webook@tcp(${region}.slave.meoying.com:3306)/?charset=utf8mb4&parseTime=True
        placeholders:
        region:
          ref:variables.region2
  cos_ds:
    #  这里的引用有限制,只能datasources下的
    ref: datasources.mts_ds

tables: # 定义数据库表
  order: # 逻辑表名
    # 分片类型, 三个必备属性datasource, database,table
    sharding:
      datasource:
        master: root:root@tcp(127.0.0.1:13306)/?charset=utf8mb4&parseTime=True&loc=Local
        slave: root:root@tcp(127.0.0.1:13306)/?charset=utf8mb4&parseTime=True&loc=Local
      database:
        order_db:
          template:
            expr: "local_sharding_plugin_db_${key}"
            placeholders:
              key:
                hash:
                  key: user_id
                  base: 3
      table: order_tab
  user: # 逻辑表名
    sharding:
      datasource:
        # 只能引用datasources下变量
        ref: datasources.mts_ds
      database:
        # 只能引用database下变量
        ref: databases.user_shard
      table: user_tab